<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>penjualan</name>
   <tag></tag>
   <elementGuidId>e6650f4a-c880-4e7a-8a0a-c4323b6803f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.glyphicon.glyphicon-chevron-down.navbar-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='dropdown-nested']/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6c835f5d-d0c3-4aad-8ffb-83be841ce49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-chevron-down navbar-icon</value>
      <webElementGuid>6a63b03a-7875-486f-952a-60ba1494bd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-nested&quot;)/li[@class=&quot;ripple ripple-block ng-star-inserted&quot;]/a[@class=&quot;dropdown-item dropdown-toggle&quot;]/span[@class=&quot;glyphicon glyphicon-chevron-down navbar-icon&quot;]</value>
      <webElementGuid>19f12f2e-4e7e-4e3a-b926-4d433df48ef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dropdown-nested']/li/a/span</value>
      <webElementGuid>59a441b5-4ac0-46ad-a542-0bd29fda95d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a/span</value>
      <webElementGuid>c557ed61-4507-44c9-8f7a-ce4c9f689680</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
