<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bahasa inggris</name>
   <tag></tag>
   <elementGuidId>c3f9ba2a-bf32-4d27-9e36-ad67a29481da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ripple.ripple-block > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'English')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>89d5ef4c-4d4e-48ad-b3b7-9424491d9eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>178a11f8-7dba-44be-a742-6dca99b61597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-admin-layout[1]/div[@class=&quot;layout-container&quot;]/app-admin-layout-header[1]/div[@class=&quot;header-container&quot;]/nav[1]/ul[@class=&quot;pull-right&quot;]/li[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-right&quot;]/li[@class=&quot;ripple ripple-block&quot;]/a[1]</value>
      <webElementGuid>04421638-2dd0-4a70-bc15-d23b70ac3dd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'English')]</value>
      <webElementGuid>f0707551-0510-424d-9989-921bb00177e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan'])[1]/following::a[3]</value>
      <webElementGuid>90314259-d74d-4b00-b71c-2d76ad94c85a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan'])[1]/following::a[4]</value>
      <webElementGuid>832c4c2e-fe76-4378-b428-d0cb7a7d2bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/preceding::a[1]</value>
      <webElementGuid>728ad80d-88c1-4d4f-b80c-6d49d06faa37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wonderland'])[1]/preceding::a[2]</value>
      <webElementGuid>27f2582e-1e82-484d-92b0-546b0070fcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>2d5dfc7c-db42-4575-8bbb-31605183f934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>480336d5-d176-499f-8646-2074185af551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>80d28b45-3b8b-4c32-952a-b5cd1ed1dc53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
