<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn-Laporan-Persediaan</name>
   <tag></tag>
   <elementGuidId>15f05c86-cda5-4e4b-8154-7a90d469deeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-tabpanel-3']/div/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>718f4d5f-3142-4f1f-af30-a2ce2f330897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr1</value>
      <webElementGuid>eff584ec-6423-4bb0-a071-34f57317839a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/reports/inventory</value>
      <webElementGuid>3f6dc21f-489e-491a-b84b-14ff87458618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Persediaan </value>
      <webElementGuid>00cbe0ab-c31d-4aae-90ed-57d6b095f84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-tabpanel-3&quot;)/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;report-container ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 report-container__list-title&quot;]/a[@class=&quot;mr1&quot;]</value>
      <webElementGuid>a7eb1162-97be-47a1-878c-199e8dcb5a03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-tabpanel-3']/div/div[2]/div/div/a</value>
      <webElementGuid>bd3c1cd0-3084-466d-b5fb-96e5d94bc23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Persediaan')]</value>
      <webElementGuid>4258c70c-cbdd-4781-af82-9a0d07cc83fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[2]/following::a[2]</value>
      <webElementGuid>9eb5d9e9-db14-4007-ae25-91076fbda8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hutang'])[1]/following::a[4]</value>
      <webElementGuid>fab258c2-2d78-4710-bf04-a2fcc805bf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mutasi Persediaan'])[1]/preceding::a[2]</value>
      <webElementGuid>bbde2091-b54b-4efe-9005-76744014a4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk Stok Rendah'])[1]/preceding::a[4]</value>
      <webElementGuid>78a1b93f-fdef-43b9-b8e7-8036d726d851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Persediaan']/parent::*</value>
      <webElementGuid>f37beaea-c545-436d-a047-5f09e0aa65ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/reports/inventory')]</value>
      <webElementGuid>f565ae5e-2fc9-46ba-9f56-24b5e469dc4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-tabpanel[4]/div/div/div[2]/div/div/a</value>
      <webElementGuid>0c742748-11e2-42f5-a2bb-5ec6cca1d77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/reports/inventory' and (text() = ' Persediaan ' or . = ' Persediaan ')]</value>
      <webElementGuid>accde463-26eb-47e6-bd80-6ffb6d3f225f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
