<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-select-date</name>
   <tag></tag>
   <elementGuidId>8d7a1d42-f9b6-4b72-bb5a-1d345dd619b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ui-datepicker-trigger.ui-calendar-button.ng-tns-c23-8.ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-icon-only.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edc77426-1bdb-437a-8e22-2b4920cfe003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger ui-calendar-button ng-tns-c23-8 ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ng-star-inserted</value>
      <webElementGuid>c4e4cfcd-0a70-4401-93ea-9a81de5a3673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>80bb4cb0-dd06-45c2-9428-0ce4f096bb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9cb26e9-7f4f-40a7-92f0-26d673681808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ui-btn</value>
      <webElementGuid>2a65fdbe-fda8-4f57-a110-77c6d8fc4548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-admin-layout[1]/div[@class=&quot;layout-container&quot;]/main[@class=&quot;main-container&quot;]/section[@class=&quot;container container-lg&quot;]/app-base-rfpage[@class=&quot;ng-star-inserted&quot;]/app-reports-inventory-preview[@class=&quot;ng-star-inserted&quot;]/app-base-comp[1]/div[@class=&quot;ng-star-inserted&quot;]/app-base-report[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;well well-lg ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-valid ng-touched&quot;]/div[1]/div[@class=&quot;form-group&quot;]/p-calendar[@class=&quot;ng-tns-c23-8 ng-pristine ng-valid ng-touched&quot;]/span[@class=&quot;ng-tns-c23-8 fw ui-calendar ui-calendar-w-btn&quot;]/button[@class=&quot;ui-datepicker-trigger ui-calendar-button ng-tns-c23-8 ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ng-star-inserted&quot;]</value>
      <webElementGuid>668b3c7f-b307-4cf5-a967-55897e79a557</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>aaa43fdd-3182-4650-970b-95d358c062c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per tanggal'])[1]/following::button[1]</value>
      <webElementGuid>06b0a8c5-2f84-4b4a-9941-3c6f5ce6d17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::button[1]</value>
      <webElementGuid>c715ed98-59ae-4c96-9c81-7a18691d4bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU'])[1]/preceding::button[1]</value>
      <webElementGuid>9bd94f84-0fd0-48e0-9359-518ee7fd360b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>99b43f3b-7635-4b37-b165-700262c46d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ui-btn' or . = 'ui-btn')]</value>
      <webElementGuid>114b25d8-0308-4e84-ad9f-a326272e1345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
