<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pembelian</name>
   <tag></tag>
   <elementGuidId>a21a6e84-d9df-4e9c-a554-2b75eb5f2fbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='dropdown-nested']/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d4e9a83a-a3dd-487f-99e8-a9cac54148ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-chevron-down navbar-icon</value>
      <webElementGuid>ab1786dc-0f8e-49e8-bc74-33fb348c8cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-nested&quot;)/li[@class=&quot;ripple ripple-block&quot;]/a[@class=&quot;dropdown-item dropdown-toggle&quot;]/span[@class=&quot;glyphicon glyphicon-chevron-down navbar-icon&quot;]</value>
      <webElementGuid>424e6674-68a7-4da9-a822-47f11f4b27d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dropdown-nested']/li[2]/a/span</value>
      <webElementGuid>d4b39c53-4cd6-4874-aa57-7422fb96a7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a/span</value>
      <webElementGuid>c2fdcf07-e495-472c-8edf-8022c83723cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
